# -*- coding: utf-8 -*-

import json

symbols = [
 {
  "voice": "-", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "p", 
  "del. rel.": "-", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "+", 
  "high": "0", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "b", 
  "del. rel.": "-", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "+", 
  "high": "0", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "-", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "+", 
  "symbol": "ɸ", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "+", 
  "high": "0", 
  "strid": "-", 
  "ant": "0", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "+", 
  "symbol": "β", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "+", 
  "high": "0", 
  "strid": "-", 
  "ant": "0", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "-", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "-", 
  "symbol": "f", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "+", 
  "high": "0", 
  "strid": "+", 
  "ant": "0", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "-", 
  "symbol": "v", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "+", 
  "high": "0", 
  "strid": "+", 
  "ant": "0", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "-", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "+", 
  "symbol": "t̪", 
  "del. rel.": "-", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "-", 
  "ant": "+", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "+", 
  "symbol": "d̪", 
  "del. rel.": "-", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "-", 
  "ant": "+", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "-", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "+", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "+", 
  "symbol": "θ", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "-", 
  "ant": "+", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "+", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "+", 
  "symbol": "ð", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "-", 
  "ant": "+", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "-", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "-", 
  "symbol": "t", 
  "del. rel.": "-", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "-", 
  "ant": "+", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "-", 
  "symbol": "d", 
  "del. rel.": "-", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "-", 
  "ant": "+", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "-", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "-", 
  "symbol": "ʦ", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "+", 
  "ant": "+", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "-", 
  "symbol": "ʣ", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "+", 
  "ant": "+", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "-", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "+", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "-", 
  "symbol": "s", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "+", 
  "ant": "+", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "+", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "-", 
  "symbol": "z", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "+", 
  "ant": "+", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "-", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "-", 
  "symbol": "ʈ", 
  "del. rel.": "-", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "-", 
  "ant": "-", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "-", 
  "symbol": "ɖ", 
  "del. rel.": "-", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "-", 
  "ant": "-", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "-", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "+", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "-", 
  "symbol": "ʂ", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "+", 
  "ant": "-", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "+", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "-", 
  "symbol": "ʐ", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "+", 
  "ant": "-", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "-", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "+", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "+", 
  "symbol": "ʃ", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "+", 
  "ant": "-", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "+", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "+", 
  "symbol": "ʒ", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "+", 
  "ant": "-", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "-", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "+", 
  "symbol": "ʧ", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "+", 
  "ant": "-", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "+", 
  "symbol": "ʤ", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "+", 
  "ant": "-", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "-", 
  "front": "+", 
  "nas": "-", 
  "back": "-", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "c", 
  "del. rel.": "-", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "+", 
  "nas": "-", 
  "back": "-", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "ɟ", 
  "del. rel.": "-", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "-"
 }, 
 {
  "voice": "-", 
  "front": "+", 
  "nas": "-", 
  "back": "-", 
  "round": "0", 
  "cons": "+", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "ç", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "+", 
  "nas": "-", 
  "back": "-", 
  "round": "0", 
  "cons": "+", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "ʝ", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "-"
 }, 
 {
  "voice": "-", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "k", 
  "del. rel.": "-", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "g", 
  "del. rel.": "-", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "ɡ", 
  "del. rel.": "-", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "-"
 }, 
 {
  "voice": "-", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "0", 
  "cons": "+", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "x", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "0", 
  "cons": "+", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "ɣ", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "-"
 }, 
 {
  "voice": "-", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "q", 
  "del. rel.": "-", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "ɢ", 
  "del. rel.": "-", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "-"
 }, 
 {
  "voice": "-", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "0", 
  "cons": "+", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "χ", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "0", 
  "cons": "+", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "ʁ", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "-"
 }, 
 {
  "voice": "-", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "0", 
  "cons": "+", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "-", 
  "dist": "0", 
  "symbol": "ħ", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "+"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "0", 
  "cons": "+", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "-", 
  "dist": "0", 
  "symbol": "ʕ", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "+"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "+", 
  "back": "0", 
  "round": "-", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "m", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "+", 
  "high": "0", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "-", 
  "cons": "+", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "ʙ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "+", 
  "high": "0", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "+", 
  "back": "0", 
  "round": "-", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "ɱ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "+", 
  "high": "0", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "-", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "ⱱ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "+", 
  "high": "0", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "+", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "+", 
  "symbol": "n̪", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "0", 
  "ant": "+", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "+", 
  "symbol": "l̪", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "0", 
  "strid": "0", 
  "ant": "+", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "+", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "+", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "-", 
  "symbol": "n", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "0", 
  "ant": "+", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "-", 
  "symbol": "l", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "0", 
  "strid": "0", 
  "ant": "+", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "+", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "-", 
  "symbol": "ɾ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "0", 
  "strid": "0", 
  "ant": "+", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "+", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "-", 
  "symbol": "r", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "0", 
  "strid": "0", 
  "ant": "+", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "+", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "-", 
  "symbol": "ɳ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "0", 
  "ant": "-", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "-", 
  "symbol": "ɭ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "0", 
  "strid": "0", 
  "ant": "-", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "+", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "-", 
  "symbol": "ɽ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "0", 
  "strid": "0", 
  "ant": "-", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "+", 
  "nas": "+", 
  "back": "-", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "ɲ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "-", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "+", 
  "nas": "-", 
  "back": "-", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "ʎ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "+", 
  "syll": "-", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "+", 
  "back": "+", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "ŋ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "-", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "ʟ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "+", 
  "syll": "-", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "+", 
  "back": "+", 
  "round": "0", 
  "cons": "+", 
  "cont": "-", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "ɴ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "-", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "0", 
  "cons": "+", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "ʀ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "-", 
  "low": "-"
 }, 
 {
  "voice": "-", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "-", 
  "cont": "-", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "ʔ", 
  "del. rel.": "-", 
  "c.g.": "+", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "-", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "h", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "-", 
  "s.g.": "+", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "ɦ", 
  "del. rel.": "+", 
  "c.g.": "-", 
  "approx": "-", 
  "labial": "-", 
  "high": "0", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "-", 
  "s.g.": "+", 
  "son": "-", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "+", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "w", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "+", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "-", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "ʋ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "+", 
  "high": "0", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "-", 
  "symbol": "ɹ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "0", 
  "strid": "0", 
  "ant": "+", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "0", 
  "nas": "-", 
  "back": "0", 
  "round": "0", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "+", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "ɻ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "0", 
  "strid": "0", 
  "ant": "+", 
  "dorsal": "-", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "-", 
  "low": "0"
 }, 
 {
  "voice": "+", 
  "front": "+", 
  "nas": "-", 
  "back": "-", 
  "round": "-", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "j", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "-", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "+", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "0", 
  "dist": "0", 
  "symbol": "ɥ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "+", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "-", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "+", 
  "nas": "-", 
  "back": "-", 
  "round": "-", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "+", 
  "dist": "0", 
  "symbol": "i", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "+", 
  "nas": "-", 
  "back": "-", 
  "round": "+", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "+", 
  "dist": "0", 
  "symbol": "y", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "+", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "-", 
  "round": "-", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "+", 
  "dist": "0", 
  "symbol": "ɨ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "-", 
  "round": "+", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "+", 
  "dist": "0", 
  "symbol": "ʉ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "+", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "-", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "+", 
  "dist": "0", 
  "symbol": "ɯ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "+", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "+", 
  "dist": "0", 
  "symbol": "u", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "+", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "+", 
  "nas": "-", 
  "back": "-", 
  "round": "-", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "-", 
  "dist": "0", 
  "symbol": "ɪ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "+", 
  "nas": "-", 
  "back": "-", 
  "round": "+", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "-", 
  "dist": "0", 
  "symbol": "ʏ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "+", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "-", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "-", 
  "dist": "0", 
  "symbol": "ʊ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "+", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "+", 
  "nas": "-", 
  "back": "-", 
  "round": "-", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "+", 
  "dist": "0", 
  "symbol": "e", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "+", 
  "nas": "-", 
  "back": "-", 
  "round": "+", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "+", 
  "dist": "0", 
  "symbol": "ø", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "+", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "-", 
  "round": "-", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "+", 
  "dist": "0", 
  "symbol": "ɘ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "-", 
  "round": "+", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "+", 
  "dist": "0", 
  "symbol": "ɵ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "+", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "-", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "+", 
  "dist": "0", 
  "symbol": "ɤ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "+", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "+", 
  "dist": "0", 
  "symbol": "o", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "+", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "-", 
  "round": "-", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "-", 
  "dist": "0", 
  "symbol": "ə", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "+", 
  "nas": "-", 
  "back": "-", 
  "round": "-", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "-", 
  "dist": "0", 
  "symbol": "ɛ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "+", 
  "nas": "-", 
  "back": "-", 
  "round": "+", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "-", 
  "dist": "0", 
  "symbol": "œ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "+", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "-", 
  "round": "-", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "-", 
  "dist": "0", 
  "symbol": "ɜ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "-", 
  "round": "+", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "-", 
  "dist": "0", 
  "symbol": "ɞ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "+", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "-", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "-", 
  "dist": "0", 
  "symbol": "ʌ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "+", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "-", 
  "dist": "0", 
  "symbol": "ɔ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "+", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "-"
 }, 
 {
  "voice": "+", 
  "front": "+", 
  "nas": "-", 
  "back": "-", 
  "round": "-", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "+", 
  "dist": "0", 
  "symbol": "æ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "+"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "-", 
  "round": "-", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "+", 
  "dist": "0", 
  "symbol": "ɐ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "+"
 }, 
 {
  "voice": "+", 
  "front": "+", 
  "nas": "-", 
  "back": "-", 
  "round": "-", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "-", 
  "dist": "0", 
  "symbol": "a", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "+"
 }, 
 {
  "voice": "+", 
  "front": "+", 
  "nas": "-", 
  "back": "-", 
  "round": "+", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "-", 
  "dist": "0", 
  "symbol": "ɶ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "+", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "+"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "-", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "-", 
  "dist": "0", 
  "symbol": "ɑ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "-", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "+"
 }, 
 {
  "voice": "+", 
  "front": "-", 
  "nas": "-", 
  "back": "+", 
  "round": "+", 
  "cons": "-", 
  "cont": "+", 
  "coronal": "-", 
  "ATR": "-", 
  "dist": "0", 
  "symbol": "ɒ", 
  "del. rel.": "0", 
  "c.g.": "-", 
  "approx": "+", 
  "labial": "+", 
  "high": "-", 
  "strid": "0", 
  "ant": "0", 
  "dorsal": "+", 
  "s.g.": "-", 
  "son": "+", 
  "lat": "-", 
  "syll": "+", 
  "low": "+"
 }
]
